#+hugo_base_dir: .
#+hugo_auto_set_lastmod: t
* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:
** Syllabus :syllabus:
:PROPERTIES:
:EXPORT_FILE_NAME: syllabus
:END:
#+begin_description
The syllabus for Spring 2020 of the class is given below.
#+end_description
*** Course details
The class meets on Tuesday and Thursday each week, 8:30-9:45 at Engineering Lab, Rm 305.

- Instructor: Kostas Andreadis
- Office: 18C Marston Hall
- Phone: 413-545-5395
- Office Hours: Tuesdays 10:00-12:30, or by arrangement
*** Course description
This course provides an introduction to computational techniques that are applicable to environmental problems. The students are expected to attain hands-on experience with numerical and statistical programming tools and learn how to perform a series of analysis and visualization tasks. Moreover, cloud-based and massively parallel technologies will be introduced as well as fundamental computational concepts and abstractions.
*** Prerequisites
CE-ENGIN 244 (Programming for Civil Engineers), although familiarity with some basic programming concepts should suffice.
*** Course objectives
This course will introduce students to scientific programming with open source tools, focusing primarily on data analysis, visualization, and modeling. By the end of the course, the students will have learned and developed software code to ingest, process and analyze datasets (both temporal and spatial) with applications relevant to environmental engineering.
*** Course outcomes
- Understand basic programming abstractions and data structures.
- Implement basic algorithms in Python.
- Load, parse, process, and store various scientific datasets.
- Produce publication-quality plots and visualizations.
- Perform time series and spatial analyses.
- Implement statistical and machine learning algorithms for engineering problems.
- Understand basic parallelization techniques.
- Deploy algorithms on cloud architectures (AWS, Google).
- Learn good software engineering practices.
*** Homework and exams
Homework problems will be assigned each week, and will be collected electronically in the form of PDF or HTML documents. In addition, a class project will be assigned to each student[fn:1] and a final report will be due at the end of the semester in lieu of a final exam.

[fn:1] Ideally, the topic will be relevant to the student's research.
*** Grading schedule
- Homework assignments (60%)
- Class project (40%)
*** Academic honesty policy statement
Since the integrity of the academic enterprise of any institution of higher education requires honesty in scholarship and research, academic honesty is required of all students at the University of Massachusetts Amherst. Academic dishonesty including but not limited to cheating, fabrication, plagiarism, and facilitating dishonesty, is prohibited in all programs of the University. Appropriate sanctions may be imposed on any student who has committed an act of academic dishonesty. Instructors should take reasonable steps to address academic misconduct. Any person who has reason to believe that a student has committed academic dishonesty should bring such information to the attention of the appropriate course instructor as soon as possible. Instances of academic dishonesty not related to a specific course should be brought to the attention of the appropriate department Head or Chair. The procedures outlined below are intended to provide an efficient and orderly process by which action may be taken if it appears that academic dishonesty has occurred and by which students may appeal such actions. Since student are expected to be familiar with this policy and the commonly accepted standards of academic integrity, ignorance of such standards is not normally sufficient evidence of lack of intent.
For more information about what constitutes academic dishonesty, please see the Dean of Students’ website (p. 9-10): [[http://umass.edu/dean_students/codeofconduct/acadhonesty/]]
*** Disability statement
The University of Massachusetts Amherst is committed to making reasonable, effective and appropriate accommodations to meet the needs of students with disabilities and help create a barrier-free campus. If you are in need of accommodation for a documented disability, register with Disability Services to have an accommodation letter sent to your faculty. It is your responsibility to initiate these services and to communicate with faculty ahead of time to manage accommodations in a timely manner. For more information, consult the Disability Services website at [[http://www.umass.edu/disability/]].

*** Class schedule
Below you will find the days of class and the topics that will be covered on those days (subject to change depending on whether we will need to spend more time on topics that might prove more difficult than expected).

- <2020-01-21 Tue 08:30> Class overview.
- <2020-01-23 Thu 08:30> Introduction to Python.
- <2020-01-28 Tue 08:30> Data structures, functions and files.
- <2020-01-30 Thu 08:30> Coding practices. Development environment.
- <2020-02-04 Tue 08:30> Numerical Python (Numpy).
- <2020-02-06 Thu 08:30> Numerical Python (Numpy).
- <2020-02-11 Tue 08:30> Python data analysis (Pandas).
- <2020-02-13 Thu 08:30> Python data analysis (Pandas).
- <2020-02-18 Tue 08:30> No class (Monday's schedule).
- <2020-02-20 Thu 08:30> Data Input/Output (web scraping).
- <2020-02-25 Tue 08:30> Data Input/Output (files).
- <2020-02-27 Thu 08:30> Data cleaning.
- <2020-03-03 Tue 08:30> Merging and grouping datasets.
- <2020-03-05 Thu 08:30> Plotting basics.
- <2020-03-10 Tue 08:30> Interactive plotting.
- <2020-03-12 Thu 08:30> Interactive plotting.
- <2020-03-17 Tue 08:30> No class (Spring recess).
- <2020-03-19 Thu 08:30> No class (Spring recess).
- <2020-03-24 Tue 08:30> Time series.
- <2020-03-26 Thu 08:30> Statistics.
- <2020-03-31 Tue 08:30> Machine learning.
- <2020-04-02 Thu 08:30> N-dimensional analysis (Xarray).
- <2020-04-07 Tue 08:30> N-dimensional analysis (Xarray).
- <2020-04-09 Thu 08:30> Parallel computing (Dask).
- <2020-04-14 Tue 08:30> Cloud computing.
- <2020-04-16 Thu 08:30> Cloud computing.
- <2020-04-21 Tue 08:30>
- <2020-04-23 Thu 08:30>
